defaultContentLanguage: zh-Hans

params:
  displayFullLangName: true


title: Shane's Blog
theme: ["congo"]
module:
  mounts:
  - source: content
    target: content

markup:
  goldmark:
    renderer:
      unsafe: true