languageCode: "zh-Hans"
languageName: "中文"
baseURL: "https://yaozhixiang.com"
params:
  author:
    name: "CC Yiu"
    links:
    - github: "https://github.com/future0906"
    - x-twitter: "https://x.com/Shane_Yao"
weight: 5